export const SEAECH_TEXT = 'SEAECH_TEXT';
export const ERROR_SEARCH = 'ERROR_SEARCH';
export const CHANGE_CLASS_MENU = 'CHANGE_CLASS_MENU';
export const CHANGE_CLASS_MENU_BODY = 'CHANGE_CLASS_MENU_BODY';
export const CLICK_TO_CARD = 'CLICK_TO_CARD';
export const CLICK_TO_LIKES_CARD = 'CLICK_TO_LIKES_CARD';
export const GET_VISIBILITY_CART = 'GET_VISIBILITY_CART';
export const GET_VISIBILITY_FAVORIT = 'GET_VISIBILITY_FAVORIT';